version: '2'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    ports:
      - 8080:3000
    environment:
      - PORT=3000
      - DB_SPEC=postgresql://postgres:example@postgresql:5432/postgres
  postgresql:
    image: postgres:10.1-alpine
    environment:
      - POSTGRES_PASSWORD=example
